### PR TITLE
Add Progressive Web App features

### PR DESCRIPTION
**Pull request by nok-ko**
- `index.html`, `resource.html`, and the various resource pages now load offline.
- User is not able to log in, etc. while offline. Currently there's just an ugly browser error message if they try to do that.
- User can install ShakeGuard as a Progressive Web App on their smartphone through their web browser!

TBD:
- I badly want to show an offline version of the Kit page, but it's going to be a little tricky. Will see if I can do it by end of day.

### CODE REVIEW

**Comment by nok-ko** [comment]
I think it's ready to merge, currently it's live on https://shakeguard.nokko.me so give it a whirl.

**Comment by nok-ko** [comment]
[[Resources] Store articles in Browser Storage (1hr) (1) [?]](https://trello.com/c/GffIa1kc/205-resources-store-articles-in-browser-storage-1hr-1)

**Comment by nok-ko** [comment]
[Make a first pass of the offline-accessible feature (Est. 3hr) (3) [4]](https://trello.com/c/91xw81qX/281-make-a-first-pass-of-the-offline-accessible-feature-est-3hr-3-4)

**Comment by nok-ko** [comment]
We now pass Lighthouse muster for PWA stuff!

image

**Comment by nok-ko** [comment]
From commit message, highlighting it here:

> Note: BUG! We still cache `/resources` which means the login/logout buttons on `/resources` don't correctly represent the current state of the session.

**Comment by nok-ko** [comment]
Progress:
- Everything appears to work, not tested 100%
- Offline, resources pages and the login page are accessible.
    - Login page says "You are offline!" when attempting to log in while not connected.
    - Once the connection comes back online, users can log in normally
- Online, app works as normal – not tested 100%, though.
    - Of note: GET requests with an empty body and no `Cache-Control` headers are assumed to be okay to cache, this might not always be true so we should double-check everythere
    - Especially admin dashboard stuff, haven't combed through that yet
    - While online, certain resources may not be retrieved happily – this would be due to bugs in the service worker intercepting requests. I can't think of obvious ones, but I need to look thoroughly.

Overall, not quite tested, but it does appear to work. More to come tomorrow – Phew & good night.

**Comment by nok-ko** [comment]
Rebased onto dev. Ready for merge (hopefully.)

**Review by AlexLLKong — APPROVED** [review]

**Pull request merged**
