### PR TITLE
Add “Resources” Features

### PR DESCRIPTION
**Pull request by ArtfulJW**

### CODE REVIEW

**Comment by nok-ko** [comment]
Rebased on `dev` without any conflicts. @ArtfulJW make sure to `git pull --rebase` to catch up with the force-pushed changes.

**Review by AlexLLKong — COMMENTED** [review]
I feel like the log files shouldn't be committed to the repo

**Comment by nok-ko** [comment]
Rebased on `dev` without any conflicts. @ArtfulJW make sure to `git pull --rebase` to catch up with the force-pushed changes.

**Comment by nok-ko** [comment]
Still WIP:
- Query params
- Templating for resource pages instead of serving them all individually
- Service worker for offline access

**Review by AlexLLKong — APPROVED** [review]
I feel like the log files shouldn't be committed to the repo

**Pull request merged**
