### PR TITLE
Add an admin dashboard

### LINKED ISSUE #28: Make sure when the user logs in, and is an admin, they are redirected to the admin dashboard.

### PR DESCRIPTION
**Pull request by nok-ko**
## What this does
- [x] Adds an Admin Dashboard at the `/dashboard` GET endpoint
- [x] Admin users are redirected to the dashboard when they log in.
    - Closes #28.
    - [ ] And when they access the `/profile` GET endpoint
- [ ] Regular users are prevented from accessing the `/dashboard` endpoint, redirected to `/profile` instead.
- [x] There is a list of users retrieved in JSON format via the `/profiles` endpoint.

### CODE REVIEW

**Comment by nok-ko** [comment]
Add screenshots when you have em, @speakingoftime! :)

**Comment by speakingoftime** [comment]
Screenshots of current progress:
Screen Shot 2022-05-09 at 7 09 59 PM

with media query:
Screen Shot 2022-05-09 at 7 10 14 PM

**Comment by speakingoftime** [comment]
Updated heading colour, margin

Screen Shot 2022-05-09 at 7 21 35 PM

**Comment by nok-ko** [comment]
First iteration, connecting it to the DB:

image

**Comment by nok-ko** [comment]
So, latest commits implement the `GET /profiles` endpoint & add some simple client code that fetches users from the backend. Pagination TBD. (Also, I need to generate more example users to test with… 🤔)

**Comment by nok-ko** [comment]
Kind of went nuts with the JSDoc comments, apologies in advance.

**Comment by speakingoftime** [comment]
Summary:

- New button colour variant for button-secondary! The page could use some teal (our main colour), is very yellow and grey
image

- New look and layout for the user list items (in larger screen size, the users show as 2 columns instead of 1; can fit more users on screen)

image

image



Also included empty <header> and <footer> elements for content to be inserted via js

**Comment by nok-ko** [comment]
Now with animated toasts! Have yet to hook them up to error cases, but they work:

https://user-images.githubusercontent.com/13428215/167929990-2a2121f5-cdbb-47ce-bdd6-14409e85a2a8.mp4

**Comment by nok-ko** [comment]
How to use the new `ToastQueue` class, in a nutshell:

```js
// Use the global `toastQueue` singleton to queue toasts.
toastQueue.queueToast({message: "Good job, user!", classes: ["info"]})
// That `classes` property determines which classes the resulting toast should get.
// You can also check whether there are toasts in the queue right now by reading 
// `toastQueue.toasting` – may be useful for weird UI edge cases.
// Code is pretty well-documented, I tried to JSDoc all the things.
```

**Comment by nok-ko** [comment]
## TODO:
- [ ] Restyle toasts to actually look good (@speakingoftime ?)
- [ ] Move `ToastQueue` to its own module
    - Might look into bundlers in the future… far future.
- [ ] Remove example toast code

**Comment by nok-ko** [comment]
[Pretty toast/alert UI Features for admin dashboard (1hr) (1) [2.5]](https://trello.com/c/7jICyNnj/134-pretty-toast-alert-ui-features-for-admin-dashboard-1hr-1-25)

**Comment by speakingoftime** [comment]
## TODO:
- [ ] Review code for edit and delete admin buttons (please help, @nok-ko)
- I wasn't able to submit edits I made to my and Jay's name, but was able to for yours and Alex

**Comment by nok-ko** [comment]
Oops. Looks like my latest change breaks all interaction on the page, one moment.

**Comment by nok-ko** [comment]
> Oops. Looks like my latest change breaks all interaction on the page, one moment.

Latest commit fixes this

**Comment by nok-ko** [comment]
> ## TODO:
> 
>     * [x]  Review code for edit and delete admin buttons (please help, @nok-ko)
> 
>     * I wasn't able to submit edits I made to my and Jay's name, but was able to for yours and Alex

@speakingoftime: latest commit fixes it: issue was mostly on the database end, all the `_id` fields *should* have been `ObjectId`s, but it seems the old data used strings instead. One-line fix in the code:

```diff
--	const filterQuery = {'_id': req.body._id};
++ 	const filterQuery = {'_id': new mdb.ObjectId(req.body._id)};
```

**Comment by speakingoftime** [comment]
Popup form styled, but doesn't create new admin when "create admin" button is clicked
I'd like to make the form pop up on screen a smoother experience, but that's for another time

https://user-images.githubusercontent.com/97325915/167957509-3ab2afc2-821b-4a66-8077-b447492796ff.mov

**Comment by nok-ko** [comment]
We should impl. the features in #22 as well!

**Comment by speakingoftime** [comment]
demo of the add, delete actions, and toasts in action:

https://user-images.githubusercontent.com/97325915/168111655-b716301d-cbba-49ba-a5fe-4199e71e9e73.mp4

**Comment by speakingoftime** [comment]
I fixed the bug you mentioned @nok-ko how the "Saved successfully" message displayed even when it wasn't supposed to. Plus added some nice colours to better show which admins are being actively edited!

Also added a short toast that confirms that an image/file has been uploaded when creating an admin

https://user-images.githubusercontent.com/97325915/168203202-01f1bb59-9ff3-4767-8566-47bd4f84aac6.mp4

**Comment by nok-ko** [comment]
> I fixed the bug you mentioned @nok-ko how the "Saved successfully" message displayed even when it wasn't supposed to.

@speakingoftime The UI is really coming along nicely, great work! New toasts are nice, thanks a bunch. 

Do you handle server errors as well? What happens if you stop the server, then try to submit an edit?

**Comment by speakingoftime** [comment]
> > I fixed the bug you mentioned @nok-ko how the "Saved successfully" message displayed even when it wasn't supposed to.
> 
> @speakingoftime The UI is really coming along nicely, great work! New toasts are nice, thanks a bunch.
> 
> Do you handle server errors as well? What happens if you stop the server, then try to submit an edit?

I did not....would doing this be enough?

image

**Comment by nok-ko** [comment]
> > > I fixed the bug you mentioned @nok-ko how the "Saved successfully" message displayed even when it wasn't supposed to.
> > 
> > 
> > @speakingoftime The UI is really coming along nicely, great work! New toasts are nice, thanks a bunch.
> > Do you handle server errors as well? What happens if you stop the server, then try to submit an edit?
> 
> I did not....would doing this be enough?
> 
> image

I think you might have to wrap the fetch in a `try…catch`, not sure if just `response.ok` will catch it in the case that the server really is down. Try it and see! Start the server, log in, start editing, stop the server (`Ctrl-C` in the terminal window to end the process), then make the request.

**Comment by speakingoftime** [comment]
very basic try catch

https://user-images.githubusercontent.com/97325915/168209766-835cd609-dd1e-43ad-91f0-f3351b2657c7.mov

image

**Comment by nok-ko** [comment]
Nicely done!

**Review by speakingoftime — COMMENTED** [review]
How it looks:
https://user-images.githubusercontent.com/97325915/168336061-8412fb79-dcf9-42a4-9b31-0f5c89573638.mov

**Comment by nok-ko** [comment]
[Code review and merge branches (1hr) (1) [4]](https://trello.com/c/kh3fiDMq/178-code-review-and-merge-branches-1hr-1-4)

**Review by AlexLLKong — APPROVED** [review]

**Pull request merged**
