### PR TITLE
Integrate Frontend & Backend code!

### PR DESCRIPTION
**Pull request by nok-ko**
- [x] Make the login page log users in
- [x] Make a placeholder “profile” page that has a “Logout” button
- [x] Use the session cookie to track a user's logged-in status. (TODO: Improve session handling… put who the user is, in the cookie…)
    - Thanks @AlexLLKong!
- [x] Remove extraneous files
- [x] Refactor old client code
- [x] Make all JS files `"use strict";`

### CODE REVIEW

**Review by AlexLLKong — COMMENTED** [review]
LGTM!

**Review by AlexLLKong — APPROVED** [review]
LGTM!

**Comment by nok-ko** [comment]
Wonderful.

**Comment by nok-ko** [comment]
[Integrate Backend API into Front-End code. (2hr)](https://trello.com/c/Ld5CjcdZ/107-integrate-backend-api-into-front-end-code-2hr)

**Pull request merged**
