### PR TITLE
Improve logging.

### PR DESCRIPTION
**Pull request by nok-ko**
Adds HTTP logging via `morgan`.

Start on converting `console.log` calls to use a proper logging library, probably `winston`.

### CODE REVIEW

**Comment by nok-ko** [comment]
Adds a `--devLog` option. By default, HTTP responses other than `1xx`, `2xx`, and `3xx` are logged to standard out, and everything is logged to the `logs/access.log` file. With `--devLog`, everything is logged to standard out, no filtering.

**Comment by nok-ko** [comment]
Currently, logs look like this with `--devLog`:
image

And this is the output in the log file:
```log
::ffff:127.0.0.1 - - [16/May/2022:18:13:25 +0000] "GET / HTTP/1.1" 304 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:100.0) Gecko/20100101 Firefox/100.0"
::ffff:127.0.0.1 - - [16/May/2022:18:13:25 +0000] "GET /css/index.css HTTP/1.1" 304 - "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:100.0) Gecko/20100101 Firefox/100.0"
::ffff:127.0.0.1 - - [16/May/2022:18:13:25 +0000] "GET /css/header-footer.css HTTP/1.1" 304 - "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:100.0) Gecko/20100101 Firefox/100.0"
::ffff:127.0.0.1 - - [16/May/2022:18:13:25 +0000] "GET /images/menu-icon-black.svg HTTP/1.1" 200 132 "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:100.0) Gecko/20100101 Firefox/100.0"
::ffff:127.0.0.1 - - [16/May/2022:18:13:25 +0000] "GET /images/comp2800_logo.svg HTTP/1.1" 304 - "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:100.0) Gecko/20100101 Firefox/100.0"
::ffff:127.0.0.1 - - [16/May/2022:18:13:25 +0000] "GET /css/buttons.css HTTP/1.1" 200 2144 "http://localhost:8000/css/header-footer.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:100.0) Gecko/20100101 Firefox/100.0"
::ffff:127.0.0.1 - - [16/May/2022:18:13:25 +0000] "GET /images/comp2800_logo_favicon.ico HTTP/1.1" 200 4286 "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:100.0) Gecko/20100101 Firefox/100.0"
::ffff:127.0.0.1 - - [16/May/2022:18:13:25 +0000] "GET /images/ali-kazal-jwyFn9kxQuc-unsplash.jpg HTTP/1.1" 304 - "http://localhost:8000/css/index.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:100.0) Gecko/20100101 Firefox/100.0"
```

**Comment by nok-ko** [comment]
And this is the stdout log without `--devLog`, just shows the errors:
image

**Comment by nok-ko** [comment]
[Make our logging better with a logging library and a command-line argument. (Est. 2hrs) (2) [?]](https://trello.com/c/njRYJn3i/208-make-our-logging-better-with-a-logging-library-and-a-command-line-argument-est-2hrs-2)

**Comment by nok-ko** [comment]
Added `winston`! Donezo, basically ready for review.

**Review by AlexLLKong — APPROVED** [review]

**Comment by nok-ko** [comment]
Closed #25!

**Pull request merged**
